mlp_params = dict(hidden_layer_sizes=(100, 4),
                  activation='relu',
                  solver='adam',
                  alpha=0.0001,
                  batch_size='auto',
                  learning_rate='constant',
                  learning_rate_init=0.001,
                  power_t=0.5, max_iter=400,
                  shuffle=True,
                  random_state=43,
                  tol=0.0001,
                  verbose=False,
                  warm_start=False,
                  early_stopping=True,
                  validation_fraction=0.35,
                  beta_1=0.9,
                  beta_2=0.999,
                  epsilon=1e-08,
                  n_iter_no_change=10)
